In [ ]:
# start Numpy 
# NumPy= Numerical Python


In [25]:
distance=[20,34,67,89]
time=[45,98,56,56]
speed=distance/time
speed
# we cannot operate on list element


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [26]:
import numpy as np


In [28]:
d=np.array(distance)
t=np.array(time)
speed=d/t
speed

array([0.44444444, 0.34693878, 1.19642857, 1.58928571])

In [29]:
type(speed)

numpy.ndarray

In [30]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [31]:
a=np.array([[[[1,2,3]]]])
a

array([[[[1, 2, 3]]]])

In [33]:
a=np.array([[1,2],[4,5]])
a

array([[1, 2],
       [4, 5]])

In [34]:
#dimension
a.ndim

2

In [35]:
#shape
a.shape

(2, 2)

In [37]:
#datatype
a.dtype

dtype('int32')

In [38]:
#total number of element in array  
a.size

4

In [43]:
b=np.array([[1,2,4,5,7,8],[4,6,8,9,5,74]])
b

array([[ 1,  2,  4,  5,  7,  8],
       [ 4,  6,  8,  9,  5, 74]])

In [44]:
states = np.array(["guj","maha","mp","up","ap","tn","wb","or","uk","pun"])
states

array(['guj', 'maha', 'mp', 'up', 'ap', 'tn', 'wb', 'or', 'uk', 'pun'],
      dtype='<U4')

In [47]:
states[5:9]

array(['tn', 'wb', 'or', 'uk'], dtype='<U4')

In [48]:
states[2:4]

array(['mp', 'up'], dtype='<U4')

In [49]:
a

array([[1, 2],
       [4, 5]])

In [50]:
a[1][0]

4

In [ ]:
a[1][0]

In [64]:
a

array([[1, 2],
       [4, 5]])

In [68]:
a[0:,1:]

array([[2],
       [5]])

array([[2, 3],
       [5, 6]])

In [71]:
a[1:,0:]

array([[4, 5]])

In [72]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a[1,1:3]

array([5, 6])

In [96]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [84]:
b=np.array([[1,2],[4,5]])
b

array([[1, 2],
       [4, 5]])

In [95]:
b[0:2,1:]

array([[2],
       [5]])

In [75]:
import numpy as np

In [7]:
print(n1)

NameError: name 'n1' is not defined

In [8]:
import numpy as np

In [9]:
n1=np.array([1,2,4,6,7])

In [10]:
n1

array([1, 2, 4, 6, 7])

In [11]:
n2=np.array([[3,4,5,7,6],[9,8,4,6,2]])
n2

array([[3, 4, 5, 7, 6],
       [9, 8, 4, 6, 2]])

In [12]:
type(n2)

numpy.ndarray

In [13]:
type(n1)

numpy.ndarray

In [15]:
# initialize numpy array with zeros 
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [16]:
n2=np.zeros((5,2))
n2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n3=np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
n4=np.zeros((1,3))

In [20]:
n4

array([[0., 0., 0.]])

In [100]:
#basic operations in array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
b=np.array([[1,2,5],[34,66,10],[8,2,9]])

In [104]:
a+b

array([[ 2,  4,  8],
       [38, 71, 16],
       [15, 10, 18]])

In [105]:
a-b

array([[  0,   0,  -2],
       [-30, -61,  -4],
       [ -1,   6,   0]])

In [106]:
b-a

array([[ 0,  0,  2],
       [30, 61,  4],
       [ 1, -6,  0]])

In [107]:
a*b

array([[  1,   4,  15],
       [136, 330,  60],
       [ 56,  16,  81]])

In [108]:
a/b

array([[1.        , 1.        , 0.6       ],
       [0.11764706, 0.07575758, 0.6       ],
       [0.875     , 4.        , 1.        ]])

In [111]:
b%a

array([[0, 0, 2],
       [2, 1, 4],
       [1, 2, 0]], dtype=int32)

In [112]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [113]:
b>50

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [115]:
a==10

True

In [117]:
b[b<30]

array([ 1,  2,  5, 10,  8,  2,  9])

In [ ]:
q. create an array of two students getting marks in 5 subjects . if the marks 
is less than 50 , print the value of those marks from the array 

In [119]:
import numpy as np
std=np.array([[67,82,79,35,20],[83,38,29,90,40]])

std[std<50]
    

array([35, 20, 38, 29, 40])

In [121]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [124]:
#logical operatoin in numpy
a>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [126]:
a[(a>5)&(a<8)]

array([6, 7])

In [128]:
b[(b!=10)|(b>30)]

array([20, 30, 40, 50, 60, 70, 80, 90])

In [129]:
c=a+b
c

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [136]:
for i in a:
    #print(i)
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [137]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
a1=a
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
a1[1][1]=50
a1

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [140]:
a

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [141]:
#it is shallow copy 
a1=a.view()
a1

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [142]:
a1[1][1]=5
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
# it is deep copy means it doesnt change the copy value
a2=a.copy()
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
a2[1][1]=50
a2

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [146]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.asarray()

In [147]:
#universal function
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [149]:
from numpy import pi
np.sin(2*pi)

-2.4492935982947064e-16

In [150]:
np.cos(pi)

-1.0

In [152]:
# floor and ceiling
print(np.floor(np.array([12.34,-9.45,16.34,10.02])))
np.ceil(np.array([12.34,-9.45,16.34,10.02]))

[ 12. -10.  16.  10.]


array([13., -9., 17., 11.])

In [153]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [154]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [155]:
#shape manipulation
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
np.shape(a)

(3, 3)

In [160]:
# reshape the array without change in actual 'a array'
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [161]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [162]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
#change the shape of array and also change the actual 'a array'
a.resize(9,1)

In [164]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [166]:
anew=a.reshape(3,3)

In [167]:
anew

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [169]:
anew

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
#chnage the array in one-d without change actual array a
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [172]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [176]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [178]:
np.hsplit(arr,2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [180]:
np.hsplit(arr,3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [182]:
#Broadcasting means adding/subtract/multiply in array
arr+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22]])

In [183]:
arr**2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144]], dtype=int32)

In [184]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [186]:
#transposr it will change the row in column, column in row..
arr.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [187]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [188]:
np.trace(arr)

9