In [ ]:
# logical operator in numpy.ndarray
a[(a>5)&(a<8)]

In [ ]:
b[(b!=10)|(b>30)]


In [2]:
import numpy as np

In [5]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
for i in a:
    for j in i:
        print(j)

10
20
30
40
50
60
70
80
90


In [ ]:
# sallow copy
a[1][1]=50

In [7]:
a2=a.view()
a2[1][1]=5

In [8]:
a2

array([[10, 20, 30],
       [40,  5, 60],
       [70, 80, 90]])

In [ ]:
a

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [9]:
np.asarray()

TypeError: asarray() missing 1 required positional argument: 'a'

In [10]:
#universal function
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
from numpy import pi

In [13]:
np.sin(2*pi)

NameError: name 'pi' is not defined

In [14]:
np.cos(pi)

NameError: name 'pi' is not defined

In [15]:
#floor and ceiling
print(np.floor(np.array([12.34,-9.45,16.32,10.02])))

[ 12. -10.  16.  10.]


In [16]:
print(np.ceil(np.array([12.34,-9.45,16.32,10.02])))

[13. -9. 17. 11.]


In [17]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [18]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [19]:
#shape manipulation
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#reshape() does not changes the original array but only returns the changed array,
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [25]:
#resize() method returns nothing and directly changes the original array
a.resize(1,9)

In [26]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#(i) Return copy of original array
#(ii) If you modify any value of this array value of original array is not affected.

a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#(i) Return only reference/view of original array
#(ii) If you modify the array you would notice that the value of original array also changes.
a.ravel()
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
a


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
a.resize(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
np.hsplit(arr,2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [40]:
# broad casting
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
a*100

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [44]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [48]:
#TRanspos
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
np.trace(a)

15

In [54]:
a2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
np.trace(a2)

18

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.diag(a)

array([1, 5, 9])

In [59]:
np.diag(a,1)

array([2, 6])

In [60]:
np.diag(a,-1)

array([4, 8])

In [61]:
np.diag(a,-2)

array([7])

In [62]:
np.tri(5,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [63]:
np.tri(5,5,2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.tri(5,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [66]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [67]:
np.tril(a,k=1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [69]:
np.triu(a,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

In [70]:
np.triu(a,1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [71]:
np.diagflat(a)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [72]:
b=np.array([1,2,3])

In [73]:
b

array([1, 2, 3])

In [74]:
np.diagflat(b)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [75]:
print(range(8))

range(0, 8)


In [76]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [77]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [78]:
np.arange(0.2,7.8,.33)


array([0.2 , 0.53, 0.86, 1.19, 1.52, 1.85, 2.18, 2.51, 2.84, 3.17, 3.5 ,
       3.83, 4.16, 4.49, 4.82, 5.15, 5.48, 5.81, 6.14, 6.47, 6.8 , 7.13,
       7.46, 7.79])

In [79]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [82]:
np.linspace(5,30,10)

array([ 5.        ,  7.77777778, 10.55555556, 13.33333333, 16.11111111,
       18.88888889, 21.66666667, 24.44444444, 27.22222222, 30.        ])

In [84]:
np.logspace(10,50,10)

array([1.00000000e+10, 2.78255940e+14, 7.74263683e+18, 2.15443469e+23,
       5.99484250e+27, 1.66810054e+32, 4.64158883e+36, 1.29154967e+41,
       3.59381366e+45, 1.00000000e+50])

In [86]:
#random number generation


In [90]:
from numpy import random as rd

In [92]:
rd.rand(3,5) # gives random array of 3 rows 5 column

array([[0.33039634, 0.36853959, 0.47923576, 0.91558994, 0.03382536],
       [0.44014064, 0.25589164, 0.96318817, 0.35982774, 0.25091169],
       [0.21860962, 0.83259188, 0.76307018, 0.42615186, 0.71474685]])

In [93]:
rd.rand(2,2)

array([[0.54393726, 0.94393325],
       [0.55087622, 0.35133376]])

In [94]:
rd.randint(5,30,20)

array([27, 11,  7, 13, 18, 28, 28, 26, 13, 12, 10, 10, 18, 10, 11,  7, 26,
       29, 23,  8])

In [101]:
a=rd.randint(5,30,(3,3))

In [11]:
a

array([[10, 20, 30],
       [40,  5, 60],
       [70, 80, 90]])

In [103]:
x=rd.randint(5,30,(3,3))

In [104]:
x=rd.randint(5,30,(3,3))
x

array([[ 9, 10,  9],
       [13, 23, 27],
       [ 6, 12, 10]])

In [106]:
x=rd.randint(5,30,(3,3))
print(x)

[[ 6 18 27]
 [17 10 11]
 [16 14 25]]


In [107]:
x

array([[ 6, 18, 27],
       [17, 10, 11],
       [16, 14, 25]])

In [108]:
a.max()

24

In [109]:
a.min()

6

In [110]:
a.mean()

14.88888888888889

In [114]:
np.median(a)

15.0

In [115]:
np.std(a)

6.244009474767608

In [116]:
np.var(a)

38.98765432098766

In [118]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']