In [2]:
#1 create an array of shape (3,3,3) and find the dimension ,size of the array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
dimension=a.ndim
size=a.size
print(dimension,size)

2 9


In [22]:
#2 create an identity array , add 100 to the array elements , and then divide it with 3.
import numpy as np
a=np.tri(3,4)
add=a+100
add
div=add/3

In [ ]:
#3 create an array and a matrix and show any three differences using python 


In [35]:
# 4.create a random array of int,of shape 5,6 find the max,min,mean,std,var of that array
from numpy import random as rd
a=rd.randint(10,20,(5,6))
print(a)
import numpy as np
np.max(a)
print(a.min())
print(a.mean())
print(a.std())
print(a.var())

[[19 12 17 14 10 18]
 [15 12 14 17 17 11]
 [10 17 17 14 13 10]
 [12 17 18 17 18 10]
 [11 18 17 12 12 19]]
10
14.6
3.0506829836393465
9.306666666666667


In [13]:
#5. using linsspace create an array betwween 100 t0 102 , and that array should have 50 elements in it.
import numpy as np
np.linspace(100,102,50)

array([100.        , 100.04081633, 100.08163265, 100.12244898,
       100.16326531, 100.20408163, 100.24489796, 100.28571429,
       100.32653061, 100.36734694, 100.40816327, 100.44897959,
       100.48979592, 100.53061224, 100.57142857, 100.6122449 ,
       100.65306122, 100.69387755, 100.73469388, 100.7755102 ,
       100.81632653, 100.85714286, 100.89795918, 100.93877551,
       100.97959184, 101.02040816, 101.06122449, 101.10204082,
       101.14285714, 101.18367347, 101.2244898 , 101.26530612,
       101.30612245, 101.34693878, 101.3877551 , 101.42857143,
       101.46938776, 101.51020408, 101.55102041, 101.59183673,
       101.63265306, 101.67346939, 101.71428571, 101.75510204,
       101.79591837, 101.83673469, 101.87755102, 101.91836735,
       101.95918367, 102.        ])

In [10]:
# 6 what is the difference between arange and range , show it using python code.
print('the range function gives the range between 1 to n numbers of values that the user wants')
print (' but the arange function gives the n number of range in form of array')
for i in range(1,11):
    print(i)
import numpy as np
np.arange(1,10)
    

the range function gives the range between 1 to n numbers of values that the user wants
 but the arange function gives the n number of range in form of array
1
2
3
4
5
6
7
8
9
10


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# 7 create an array of 3,3 but the values of the array should be between 0 to 1

b=rd.rand(3,3)
b

array([[0.53467989, 0.81005778, 0.20286094],
       [0.52087202, 0.97106796, 0.16574391],
       [0.94271336, 0.71908001, 0.57760138]])

In [69]:
'''8 create an array of shape (3,4) the values of the array should be between 10 to 50 then filter out the value which are 
greater than 20 but less than 50''' 
np
a=np.random.randint(10,50,(3,4))
print(a)
for i in a:
    #print(i)
    for j in i:
        print(j)
        if j%2==0:
            a[i][j]=0
        

#a[a>50]        
#a[(a>20)&(a<50)]
print(a)

[[44 24 18 47]
 [38 41 34 20]
 [14 33 30 13]]
44


IndexError: index 44 is out of bounds for axis 0 with size 3

In [65]:
#9 using python prove that a.a-1 = identity array.
a=np.array([[1,2,3],[4,5,6]])
b=np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square